"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

# format = """$directory \
# $git_branch\
# $git_status\
# $golang\
# $nodejs\
# $python\
# $line_break$character"""

format = """$character"""

right_format = """$directory \
$git_branch\
$git_status\
$python"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#808080'
# color_bg3 = '#665c54'
color_blue = '#458588'
# color_aqua = '#689d6a'
color_aqua = '#613514'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#614b14'

color_blue_dark = "#0e2344"

[palettes.darcubox]
fg1 = "#f0f0f0"
fg2 = "#808080"


[os]
disabled = true
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ silas ]($style)'

[directory]
style = "fg:color_bg3"
format = "[$path]($style)"
truncation_length = 10
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:color_aqua"
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
style = "bg:color_yellow"
format = '[ ($symbol $version) ]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue_dark"
format = '[ $symbol $version ]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue_dark"
format = '[( $symbol $version $virtualenv )]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = true
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
# success_symbol = '[△](bold fg:color_green)'
# error_symbol = '[△](bold fg:color_red)'
# success_symbol = '[>](bold fg:color_green)'
success_symbol = '[>>>](bold fg:#efead9)'
error_symbol = '[>>>](bold fg:#f91037)'
vimcmd_symbol = '[<N>](bold fg:color_green)'
vimcmd_replace_one_symbol = '[<R>](bold fg:color_purple)'
vimcmd_replace_symbol = '[<R>](bold fg:color_purple)'
vimcmd_visual_symbol = '[<V>](bold fg:color_yellow)'


# success_symbol = '[](bold fg:color_green)'
# error_symbol = '[](bold fg:color_red)'
# vimcmd_symbol = '[](bold fg:color_green)'
# vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
# vimcmd_replace_symbol = '[](bold fg:color_purple)'
# vimcmd_visual_symbol = '[](bold fg:color_yellow)'
